---
title: "0_data_preprocessing"
author: "Joy_Fu"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
pacman::p_load(tidyverse, lubridate)

raw_data_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/output/"

# Source in useful functions
# source("code/functions.R")
```

# Part 1. Preprocessing of AD cases
## 1. Restrict to 3-digit valid ICD (with distance metric)
```{r}
AD_encounters_raw = read_csv(file = paste0(raw_data_path, 'raw/AD_encounters_02032023.csv'), col_names = F)
colnames(AD_encounters_raw) = c("PatientID", "EncounterID", "EncounterDate", "EncounterType", "FirstADDate", "DiagnosisCode", "DiagnosisName")
dim(AD_encounters_raw) # dim = (8884165,7)
# Clean raw data
AD_encounters_clean = AD_encounters_raw %>% 
  mutate(EncounterDate = as.Date(EncounterDate), FirstADDate = as.Date(FirstADDate)) %>% 
  mutate(ICD_3digit = substr(DiagnosisCode, 1, 3)) %>% 
  select(PatientID, EncounterID, EncounterDate, ICD_3digit) %>% unique()
dim(AD_encounters_clean) # dim = (4965955,4)
rm(AD_encounters_raw)
# Keep only ICD codes in distance metrics
load('/Users/Mingzhou/Desktop/Projects/Disease.Similarity/GitHub/data/dist_final_full.rda')
icd_lst = dist_final_full %>% filter(!is.na(embed_dist)) %>% pull(ICD1) %>% unique() # N = 1619
rm_codes = grep("^[OPQVXY][0-9]+", icd_lst, value = TRUE)
icd_lst_filter = setdiff(icd_lst, rm_codes)
AD_encounters_valid = AD_encounters_clean %>% 
  filter(ICD_3digit %in% icd_lst_filter)
dim(AD_encounters_valid) # dim = (3826790,4)
```

## 2. Preprocessing of EHR features
### Merge with demographics
```{r}
# Get demographic info
AD_patients_raw = read_csv(file = paste0(raw_data_path, 'raw/AD_patients_02032023.csv'), col_names = F)
colnames(AD_patients_raw) = c("PatientID", "Sex", "PreferredLanguage", "Ethnicity", "FirstRace", "BirthDate")
dim(AD_patients_raw) # dim = (8562,6)
# Merge demo with encounters
white_group = c("White or Caucasian", "European", "White", "White: Not Listed", "Arab", "Egyptian", "Israeli", "Iranian", "Lebanese")
black_group = c("Black", "Black: African American", "Black or African American: Not Listed", "African American", "African")
american_group = c("American Indian or Alaska Native", "Armenian", "American Indian", "Caribbean/West Indian", "Indigenous")
east_asian_group = c("Asian", "Asian: Chinese", "Chinese", "Asian: Filipino", "Filipino", "Asian: Korean", "Korean",
                     "Asian: Japanese", "Japanese", "Asian: Vietnamese", "Vietnamese", "Taiwanese", "Thai", "Burmese", "Fijian")
south_asian_group = c("Asian: Pakistani", "Pakistani", "Asian: Asian Indian", "Indian (India)", "Palestinian", "Assyrian")  
pacific_group = c("Pacific Islander: Other", "Pacific Islander: Not Listed", "Pacific Islander: Native Hawaiian", "Pacific Islander: Samoan",
                  "Pacific Islander: Guamanian or Chamorro", "Native Hawaiian or Other Pacific Islander")
unknown_group = c("Choose Not to Answer", "Declined to Specify", "Do not identify with Race", "Not Listed", "NULL", "Unknown")
hispanic_group = c("Hispanic or Latino", "Hispanic/Spanish origin Other", "Puerto Rican", "Mexican, Mexican American, Chicano/a", "Cuban")
# Assign race/ethnicity groups
AD_patients_clean = AD_patients_raw %>% 
  mutate(BirthDate = as.Date(BirthDate)) %>% 
  select(PatientID, Sex, FirstRace, Ethnicity, BirthDate) %>% 
  mutate(race_ethnicity = case_when(
    Ethnicity %in% hispanic_group ~ "Hispanic",
    FirstRace %in% white_group ~ "White",
    FirstRace %in% black_group ~ "Black",
    FirstRace %in% american_group ~ "American",
    FirstRace %in% east_asian_group ~ "EastAsian",
    FirstRace %in% south_asian_group ~ "SouthAsian",
    FirstRace %in% pacific_group ~ "Pacific",
    FirstRace %in% c("Asian: Not Listed", "Asian: Other", "Other Race") ~ "Others",
    FirstRace %in% unknown_group ~ "Unknown"
  )) %>% select(PatientID, Sex, BirthDate, race_ethnicity)
# Merge together
AD_merged = AD_encounters_valid %>% left_join(AD_patients_clean) %>% 
  filter(!is.na(Sex) & !is.na(BirthDate) & Sex != "Unknown") %>% unique()
dim(AD_merged) # dim = (3315246,7)
save(AD_merged, file = paste0(raw_data_path, "mod/AD_merged.rda"))
```

### Build EHR features
```{r}
# AD diagnosis information
AD_diagnosis = AD_merged %>% filter(ICD_3digit %in% c('G30')) %>% group_by(PatientID) %>% 
  arrange(EncounterDate, .by_group = TRUE) %>% slice_head(n = 1) %>% 
  mutate(AdDiagnosisDate = EncounterDate, 
         age_AD_diagnosis = as.numeric(AdDiagnosisDate - BirthDate)/365.25) %>% 
  select(PatientID, AdDiagnosisDate, age_AD_diagnosis) %>% unique()
dim(AD_diagnosis) # dim = (8536,3)
# Get record-level features
patient_level = AD_merged %>% left_join(AD_diagnosis) %>% 
  filter(EncounterDate < AdDiagnosisDate) %>% group_by(PatientID) %>% 
  mutate(RecordStart = min(EncounterDate), 
         record_length = as.numeric(AdDiagnosisDate - RecordStart)/365.25) %>% 
  select(PatientID, RecordStart, record_length, AdDiagnosisDate, age_AD_diagnosis) %>% unique() %>% 
  filter(record_length >= 5)
dim(patient_level) # dim = (1784,5)
# Get diagnosis-level features (only keep the first time of diagnosis)
diagnosis_level = AD_merged %>% right_join(patient_level) %>% 
  filter((EncounterDate < AdDiagnosisDate) & (EncounterDate >= AdDiagnosisDate - years(5))) %>% 
  group_by(PatientID) %>% mutate(n_record = length(unique(EncounterID))) %>% ungroup() %>% 
  group_by(PatientID, ICD_3digit) %>% arrange(EncounterDate, .by_group = TRUE) %>% 
  slice_head(n = 1) %>% ungroup() %>% 
  mutate(FirstDiagnosisDate = EncounterDate, 
         age_diagnosis = as.numeric(FirstDiagnosisDate - BirthDate)/365.25,
         look_back = age_AD_diagnosis - age_diagnosis) %>% 
  select(PatientID, Sex, BirthDate, race_ethnicity, record_length, n_record, AdDiagnosisDate, 
         age_AD_diagnosis, FirstDiagnosisDate, ICD_3digit, age_diagnosis, look_back) %>% 
  unique() %>% ungroup() %>% group_by(PatientID) %>% 
  mutate(look_back_max = max(look_back)) %>% ungroup() %>% arrange(PatientID, look_back)
dim(diagnosis_level) # dim = (72847,13)
save(diagnosis_level, file = paste0(raw_data_path, "mod/diagnosis_level.rda"))
```



