---
title: "1_phenotype_screening"
author: "Joy_Fu"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
pacman::p_load(tidyverse, icd.data, gtsummary)

raw_data_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/output/"

# Source in useful functions
# source("code/functions.R")
load(file = paste0(raw_data_path, "mod/diagnosis_level.rda"))
```

# Part 1. Summary statistics of all time
```{r}
patient_summary = diagnosis_level %>% group_by(PatientID) %>% 
  mutate(n_diagnosis = length(unique(ICD_3digit))) %>% ungroup() %>% 
  select(PatientID, Sex, race_ethnicity, record_length, n_record, n_diagnosis, age_AD_diagnosis) %>% unique() %>% 
  mutate(valid = case_when(
    record_length >= 5 ~ "Yes",
    TRUE ~ "No"
  )) 
dim(patient_summary) # dim = (6404,8)
```

```{r}
patient_summary2 = patient_summary %>% select(-PatientID)
patient_summary2 %>% 
  tbl_summary(by = valid) %>% 
  add_p(pvalue_fun = ~ style_pvalue(.x, digits = 2)) %>%
  add_overall() %>%
  add_n() %>%
  modify_header(label ~ "**Variable**") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Selected in Trajectory build**") %>%
  modify_footnote(
    all_stat_cols() ~ "Median (IQR) or Frequency (%)"
  ) %>%
  modify_caption("**Table 1. Patient Characteristics**") %>%
  bold_labels()
```

## 1. Check prevalence
```{r}
icd10cm2016_3digit = icd10cm2016 %>% filter(nchar(code) == 3) %>% mutate(code = as.character(code))
prevalence_table = table(diagnosis_level$ICD_3digit) %>% as.data.frame() %>% 
  mutate(prevalence = 100*Freq/length(unique(diagnosis_level$PatientID))) %>% 
  rename(ICD = Var1) %>% left_join(icd10cm2016_3digit, by = c("ICD" = "three_digit")) %>% 
  select(ICD, Freq, prevalence, short_desc, sub_chapter, chapter) %>% unique()
prevalence_table %>% group_by(sub_chapter) %>% summarise(n_freq = sum(Freq)) %>% View()
```

## 2. Check last step before AD, and time lag
```{r}
last_diag = diagnosis_level %>% group_by(PatientID) %>% arrange(look_back) %>% 
  slice_head(n = 1) %>% select(PatientID, ICD_3digit, look_back) %>% unique()
last_diag_table = last_diag %>% group_by(ICD_3digit) %>% 
  summarise(n = n(), mean_look_back = mean(look_back, na.rm = T)) %>% 
  left_join(icd10cm2016_3digit, by = c("ICD_3digit" = "three_digit")) %>% 
  select(ICD_3digit, n, mean_look_back, short_desc, chapter) %>% unique()
```


# Part 2. Restrict to patients with at least 5 years records (lookback 5 years before AD)
## 1. AD case selection
```{r}
patient_valid_summary = patient_summary %>% filter(valid == "Yes") 
dim(patient_valid_summary) # dim = (1713,8)
# Summarize record level data
icd_prevalence_low = prevalence_table %>% 
  filter(Freq < 5) %>% pull(ICD)
record_valid_full = diagnosis_level %>% 
  filter(PatientID %in% patient_valid_summary$PatientID) %>% 
  filter(ICD_3digit %!in% icd_prevalence_low) %>% 
  group_by(PatientID) %>% 
  mutate(n_step = length(unique(FirstDiagnosisDate)),
         n_diagnosis = length(unique(ICD_3digit))) %>% ungroup() %>% 
  filter(n_step > 1)
# Finalize sample
traj_discovery_sample = record_valid_full %>% 
  select(PatientID, Sex, BirthDate, race_ethnicity, AdDiagnosisDate, age_AD_diagnosis, n_step, n_diagnosis) %>% unique()
traj_discovery_record = record_valid_full %>% 
  select(PatientID, ICD_3digit, FirstDiagnosisDate, age_diagnosis, look_back) %>% unique() 
```


```{r}
patient_lst = unique(traj_discovery_sample$PatientID) 
sample_id = 15483240

sample_traj = traj_discovery_record %>% filter(PatientID == sample_id) %>% 
  group_by(FirstDiagnosisDate) %>% mutate(step = cur_group_id())
```

```{r}
diag_dict = list()
for (i in 1:max(sample_traj$step)) {
  diag_dict[[i]] = sample_traj %>% filter(step == i) %>% pull(ICD_3digit)
}

ttt = matrix(unlist(cross(diag_dict)), ncol = 5, byrow = T)

```


```{r}

traj_lst = list()
for (i in 1:length(patient_lst)) {
  patient_id = patient_lst[i]
  records = patient_record_valid %>% filter(PatientID == patient_id) %>% 
    filter(ICD_3digit %!in% icd_prevalence_low) %>% 
    group_by(look_back) %>% slice(1) %>% arrange(look_back)
  traj_lst[i] = c(rbind(records %>% pull(ICD_3digit), records %>% pull(look_back))) %>% list()
}

len = sapply(traj_lst, length)
traj_lst_sorted = traj_lst[order(len, decreasing = T)]

len2 = sapply(traj_lst_sorted2, length)
traj_lst_sorted2 = traj_lst_sorted[c(1:175)]
```


```{r}

library("pheatmap")
pheatmap(norm_dist_matrix, cutree_rows = 4)
clusters <- hclust(as.dist(norm_dist_matrix))
plot(clusters)
```

```{r}
library("WGCNA")

embed.dist = as.dist(norm_dist_matrix)
consTree = hclust(embed.dist, method = "complete")
minModuleSize = 10
unmergedLabels = cutreeDynamic(dendro = consTree, cutHeight = NULL,
                               distM = norm_dist_matrix,
                               minClusterSize = minModuleSize)
unmergedColors = labels2colors(unmergedLabels)
table(unmergedColors)
```


```{r}
select_cluster = traj_lst_sorted[which(unmergedColors == "blue")]

traj_full = c()
for (i in select_cluster) {
  traj = i[c(TRUE, FALSE)]
  print(traj)
  traj_full = c(traj_full, traj)
}

cluster_result_addDesc = table(traj_full) %>% as.data.frame() %>% 
  left_join(icd10cm2016_3digit, by = c("traj_full" = "code")) %>% 
  select(traj_full, Freq, short_desc, sub_chapter, chapter)
```





