---
title: "2_DTW"
author: "Joy_Fu"
date: "2023-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
pacman::p_load(tidyverse, icd.data, gtsummary, dtw)

raw_data_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/AD-trajectory/output/"

# Source in useful functions
# source("code/functions.R")
load(file = '/Users/Mingzhou/Desktop/Projects/Disease.Similarity/data/Embedding.Sim/final/embed_sim_cal.rda')
dim(embed_sim_cal) # dim = (1619,1619)
embed_sim_cal[upper.tri(embed_sim_cal)] = t(embed_sim_cal)[upper.tri(embed_sim_cal)]
embed.dist = 1 - embed_sim_cal
```


# Part 1. Toy sample -- DTW development
```{r}
ref = c("G30", "F03", "I10", "E78", "M54", "F32", "F41")
eg_1 = c("G30", "F03", "M54", "I10", "E78", "F32")
eg_2 = c("G30", "F03", "I10", "M54", "E78", "F32")
eg_3 = c("G30", "F03", "I10", "E78", "F32")
eg_4 = c("G30", "J90", "R09", "C50", "G57")
eg_5 = c("G30", "I10", "M54", "F32", "F41")
eg_6 = c("G30", "F03", "I10", "E78", "F32", "F41")
eg_7 = c("G30", "F03", "F32")
eg_8 = c("G30", "M54", "F41")

dist_vec = c()
for(i in 1:7) {
  traj_dist_matrix = embed.dist[get(paste0("eg_", i)), ref]
  alignment_mvm = dtw(traj_dist_matrix, keep = TRUE, step = mvmStepPattern(20), open.end = T, open.begin = F)
  dist = alignment_mvm$normalizedDistance
  dist_vec = c(dist_vec, dist)
}

traj_dist_matrix = embed.dist[eg_6, ref]
alignment_mvm = dtw(traj_dist_matrix, keep = TRUE, step = mvmStepPattern(20), open.end = T, open.begin = F)
alignment_mvm$normalizedDistance
plot(alignment_mvm)

```

```{r}
traj_lst = list(ref, eg_1, eg_2, eg_3, eg_4, eg_5, eg_6, eg_7, eg_8)
len = sapply(traj_lst, length)
traj_lst_sorted = traj_lst[order(len, decreasing = T)]

norm_dist_full = c()
for (i in 1:length(traj_lst_sorted)) {
  traj_ref = traj_lst_sorted[[i]]
  norm_dist_vec = c(rep(NA,i-1))
  for (j in i:length(traj_lst_sorted)) {
    traj_query = traj_lst_sorted[[j]]
    traj_dist_matrix = embed.dist[traj_query,traj_ref]
    # Get time-lag matrix
    time_lag_matrix = matrix(nrow = dim(traj_dist_matrix)[1], ncol = dim(traj_dist_matrix)[2])
    # Perform alignment
    alignment_mvm = dtw(traj_dist_matrix, keep = TRUE, step = mvmStepPattern(20), open.end = T, open.begin = F)
    norm_dist = alignment_mvm$normalizedDistance
    norm_dist_vec = c(norm_dist_vec, norm_dist)
  }
  norm_dist_full = c(norm_dist_full, norm_dist_vec)
}
norm_dist_matrix = matrix(norm_dist_full, nrow = 9, ncol = 9)
norm_dist_matrix[upper.tri(norm_dist_matrix)] = t(norm_dist_matrix)[upper.tri(norm_dist_matrix)]
# clustering
heatmap(norm_dist_matrix, scale = "none")

for(i in 1:length(traj_lst_sorted)) {
  print(i)
  print(traj_lst_sorted[[i]])
}

norm_dist_full = c()
for (i in 1:length(traj_lst_sorted)) {
  traj_ref = traj_lst_sorted[[i]]
  diag_ref = traj_ref[c(TRUE, FALSE)]
  print(length(diag_ref))
  time_ref = as.numeric(traj_ref[c(FALSE, TRUE)])
  norm_dist_vec = c(rep(NA,i-1))
  for (j in i:length(traj_lst_sorted)) {
    traj_query = traj_lst_sorted[[j]]
    diag_query = traj_query[c(TRUE, FALSE)]
    time_query = as.numeric(traj_query[c(FALSE, TRUE)])
    traj_dist_matrix = embed.dist[diag_query,diag_ref]
    # Get time-lag matrix
    time_lag_matrix = matrix(nrow = dim(traj_dist_matrix)[1], ncol = dim(traj_dist_matrix)[2])
    # Perform alignment
    alignment_mvm = dtw(traj_dist_matrix, keep = TRUE, step = asymmetricP05, open.end = T, open.begin = T)
    norm_dist = alignment_mvm$distance
    norm_dist_vec = c(norm_dist_vec, norm_dist)
  }
  norm_dist_full = c(norm_dist_full, norm_dist_vec)
}

round(norm_dist_matrix, 2) 
```






```{r}
symmetric1 <- stepPattern(c(
                            1,1,1,-1,
                            1,0,0,1,
                            2,0,1,-1,
                            2,0,0,1,
                            3,1,0,-1,
                            3,0,0,1
                            ));

symmetric2 <- stepPattern(c(
                            1,1,1,-1,
                            1,0,0,2,
                            2,0,1,-1,
                            2,0,0,1,
                            3,1,0,-1,
                            3,0,0,1
                            ),"N+M");

symmetricP1 <- stepPattern(c(
                              1,1,2,-1,	# First branch: g(i-1,j-2)+
                              1,0,1,2,	#            + 2d(i  ,j-1)
                              1,0,0,1,	#            +  d(i  ,j)
                              2,1,1,-1,	# Second branch: g(i-1,j-1)+
                              2,0,0,2,	#              +2d(i,  j)
                              3,2,1,-1,	# Third branch: g(i-2,j-1)+
                              3,1,0,2,	#            + 2d(i-1,j)
                              3,0,0,1	#            +  d(  i,j)
                        ),"N+M");
asymmetricP1 <- stepPattern(c(
                              1, 1 , 2 , -1 ,
                              1, 0 , 1 , .5 ,
                              1, 0 , 0 , .5 ,
                              2, 1 , 1 , -1 ,
                              2, 0 , 0 ,  1 ,
                              3, 2 , 1 , -1 ,
                              3, 1 , 0 ,  1 ,
                              3, 0 , 0 ,  1
                              ),"N");
self_defined = stepPattern(c(
                             1,1,0,-1,
                             1,0,0,1,
                             2,1,1,-1,
                             2,0,0,1,
                             3,1,2,-1,
                             3,0,0,1
                           ),"N");
plot(asymmetricP05)
```

```{r}
alignment<-dtw(num_traj_lst[[9]][-1],num_traj_lst[[8]][-1],keep=TRUE, step=asymmetric,open.end = T, open.begin = T)
alignment$normalizedDistance
## Display the warping curve, i.e. the alignment curve
plot(alignment,type="twoway")

diffmx <- matrix( byrow=TRUE, nrow=5, c(
0, 1, 8, 2, 2, 4, 8,
1, 0, 7, 1, 1, 3, 7,
-7, -6, 1, -5, -5, -3, 1,
-5, -4, 3, -3, -3, -1, 3,
-7, -6, 1, -5, -5, -3, 1 ) )
## Cost matrix
costmx <- diffmx^2;
## Compute the alignment
al <- dtw(costmx,step.pattern=mvmStepPattern(10))
## Elements 4,5 are skipped
print(al$index2)
plot(al,main="Minimum Variance Matching alignment")
```



```{r}
icd_lst = grep("^[A-Z]", unique(c(traj_lst_sorted[[6]], traj_lst_sorted[[4]])), value = T)
dist_matrix = dist_final_full %>% 
  filter(ICD1 %in% icd_lst & ICD2 %in% icd_lst) %>% 
  select(ICD1, ICD2, embed_dist) %>% spread(key = ICD2, value = embed_dist) %>% 
  select(ICD1, "G30", "R06", "M71", "G89", "I87", "M17", "H81", "M54", "K57", "D17", "M89", "E55", "E78") %>% 
  filter(ICD1 %in% c("G30", "F03", "K21", "M12", "M25")) %>% column_to_rownames("ICD1") %>% as.matrix()
dist_matrix = dist_matrix[c(2,1,3,4,5),]

alignment<-dtw(dist_matrix,keep=TRUE, step=mvmStepPattern(5),open.end = T, open.begin = T)
alignment$normalizedDistance
## Display the warping curve, i.e. the alignment curve
plot(alignment)
```

```{r}
alignment<-dtw(num_traj_lst[[6]],num_traj_lst[[4]],keep=TRUE, step=mvmStepPattern(5),open.end = T, open.begin = T)
alignment$normalizedDistance
## Display the warping curve, i.e. the alignment curve
plot(alignment, type="twoway")
```












